version: '3'

services:
  app:
    build: .
    restart: always
    image: habilrbe
    network_mode: "host"
    volumes:
      - /var/log/saga:/opt/app/ressources
      - /home/applications/upload:/opt/app/upload/TableauEngagement
    environment:
      - APPHABIL_DB_URL=jdbc:oracle:thin:@//10.1.9.214:1561/SAEB.bna.tn
      - APPHABIL_DB_USERNAME=habil
      - APPHABIL_DB_PASSWORD=habil
      - APPHABIL_SERVER_PORT=8083
      - APPHABIL_ENV=dev
      - APPHABIL_JWT_SECRET=4e3d7a2f9b8c5d1e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e04e3d7a2f9b8c5d1e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0
      - APPHABIL_JWT_TOKEN_URI=/authenticate
      - APPHABIL_CODE_APP=BNAHABIL
      - APPHABIL_URL_AUTH=http://10.1.9.221:8082/auth/signin
      - APPHABIL_URL_ROLES=http://10.1.9.221:8082/auth/getRoles
      - APPHABIL_UPLOAD_PATH=stockage
      - APPHABIL_UPLOAD_URL_PROD=/opt/app/upload
      - APPHABIL_SMTP_HOST=bnatn.mail.protection.outlook.com
      - APPHABIL_SMTP_PORT=25
      - APPHABIL_FRONT_END_ORIGIN=http://10.1.9.27:85
