spring.datasource.url=${APPHABIL_DB_URL}
spring.datasource.username=${APPHABIL_DB_USERNAME}
spring.datasource.password=${APPHABIL_DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
server.port=${APPHABIL_SERVER_PORT:8083}
env.local=${APPHABIL_ENV:dev}
#####cors config#####
cors.allowed-origins=${APPHABIL_FRONT_END_ORIGIN}
#####upload file max size#####
spring.servlet.multipart.max-file-size=128MB
spring.servlet.multipart.max-request-size=128MB
spring.servlet.multipart.enabled=true
upload.path=${APPHABIL_UPLOAD_PATH:stockage}
upload.url.dev=${APPHABIL_UPLOAD_URL_DEV}
upload.url.prod=${APPHABIL_UPLOAD_URL_PROD}
spring.jackson.serialization.fail-on-empty-beans=false
spring.main.allow-bean-definition-overriding=true
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.filter=true
#########################################################################
local.ip=192.168.251.246
urlAuth=${APPHABIL_URL_AUTH}
urlroles=${APPHABIL_URL_ROLES}
urlNroles=http://10.1.9.221:8082/auth/signin
###############################################
jwt.secret=${APPHABIL_JWT_SECRET}
jwt.get.token.uri=${APPHABIL_JWT_TOKEN_URI}
spring.mvc.dispatch-options-request=true
codeApp=BNAHABIL
logging.level.org.apache.http=DEBUG
spring.main.allow-circular-references=true
seedoc.api.url=${APPHABIL_SEEDOC_API_URL}
########################################### SMTP #########################################
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.host=${APPHABIL_SMTP_HOST}
spring.mail.port=${APPHABIL_SMTP_PORT}
spring.mail.username=${APPHABIL_SMTP_USERNAME}
spring.mail.password=${APPHABIL_SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
###################################################
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.springframework.jdbc.datasource=DEBUG
logging.level.org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
logging.level.org.springframework.web.filter.CorsFilter=TRACE
logging.level.your.package.JwtRequestFilter=DEBUG
# Enable SQL logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# Show current schema
logging.level.org.springframework.jdbc.core=DEBUG
management.health.ldap.enabled=false
management.health.mail.enabled=false
# Expose actuator endpoints
management.endpoints.web.exposure.include=health,info,metrics,prometheus
# Enable histograms & percentiles for APIs (VERY IMPORTANT)
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.percentiles.http.server.requests=0.5,0.9,0.95,0.99
spring.application.name=BNA HABILITATION
spring.ldap.urls=ldap://10.1.9.3:389/
spring.ldap.base=DC=bnadev,DC=com
spring.ldap.username=CN=manager MANAGER,OU=Compte de services,OU=BNA,DC=bnadev,DC=com
spring.ldap.password=mot2p@ss

ldap.searchBase=OU=BNA,DC=bnadev,DC=com

logging.level.com.example.ldap=INFO

# Ignore referrals (fixes PartialResultException)
spring.ldap.base-environment.java.naming.referral=ignore

# Scheduler thread pool
spring.task.scheduling.pool.size=3

# Custom properties (optional)
interim.scheduler.retry-attempts=3
interim.scheduler.retry-delay-ms=5000