
# web directory in which are located the css file and the javascrips
directory.config = js/layout

# implementor of the CollectionInterface to use
collection.class = fr.improve.struts.taglib.layout.util.BasicCollection
collection.class.fix = fr.improve.struts.taglib.layout.renderer.FixedHeaderCollection


