#--------------------------------
# Application Log configuration
#--------------------------------
#log4j.debug=false
#log4j.rootLogger=debug
#log4j.appender.jms=org.apache.log4j.net.JMSAppender
#log4j.appender.jms.layout=org.apache.log4j.PatternLayout
#log4j.appender.jms.layout.ConversionPattern =%d{ABSOLUTE} %5p %c{1}:%L - %m%n
#log4j.appender.jms.InitialContextFactoryName=org.jnp.interfaces.NamingContextFactory
#log4j.appender.jms.ProviderURL=jnp://127.0.0.1:1099
#log4j.appender.jms.TopicBindingName=topic/testTopic
#log4j.appender.jms.TopicConnectionFactoryBindingName=ConnectionFactory

#--Console log, for development Mode
log4j.rootLogger=error,stdout,R
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern= BNA-LOG >> [%-5p][%d{dd MM yyyy HH:mm:ss}][%c][%m]%n
log4j.logger.com.oxia.fwk=error
log4j.logger.com.oxia.daoImpl=error
log4j.logger.com.oxia.quickstart=error
log4j.logger.com.bna=error




log4j.appender.R=org.apache.log4j.RollingFileAppender
log4j.appender.R.File=./smile.log
# Control the maximum log file size
log4j.appender.R.MaxFileSize=10000KB
# Archive log files (one backup file here)
log4j.appender.R.MaxBackupIndex=10
log4j.appender.R.layout=org.apache.log4j.PatternLayout
log4j.appender.R.layout.ConversionPattern=BNA-LOG >> [%-5p][%d{dd MM yyyy HH\:mm\:ss}][%c][%m]%n 



log4j.appender.MoulinetteEnvoiFichierAssurance=org.apache.log4j.RollingFileAppender
log4j.appender.MoulinetteEnvoiFichierAssurance.File=./MoulinetteEnvoiFichierAssurance.log
log4j.appender.MoulinetteEnvoiFichierAssurance.MaxFileSize=10000KB
log4j.appender.MoulinetteEnvoiFichierAssurance.MaxBackupIndex=10
log4j.appender.MoulinetteEnvoiFichierAssurance.layout=org.apache.log4j.PatternLayout
log4j.appender.MoulinetteEnvoiFichierAssurance.layout.ConversionPattern=EnvoiFichierAssurance-LOG >> [%-5p][%d{dd MM yyyy HH\:mm\:ss}][%c][%m]%n 
log4j.logger.MoulinetteEnvoiFichierAssurance= INFO , MoulinetteEnvoiFichierAssurance
